<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Voice;

class VoicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $voices = [                                              
            ['id' => 2586, 'voice' => 'Zeina', 'voice_id' => 'ar-aws-std-zeina', 'gender' => 'Female', 'language_code' => 'ar-XA', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/zeina.mp3', 'status' => 'active' , 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/1.jpg'],
            ['id' => 2587, 'voice' => 'Zhiyu', 'voice_id' => 'cn-aws-std-zhiyu', 'gender' => 'Female', 'language_code' => 'cmn-CN', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/zhiyu.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/2.jpg'],
            ['id' => 2588, 'voice' => 'Naja', 'voice_id' => 'dk-aws-std-naja', 'gender' => 'Female', 'language_code' => 'da-DK', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/naja.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/3.jpg'],
            ['id' => 2589, 'voice' => 'Mads', 'voice_id' => 'dk-aws-std-mads', 'gender' => 'Male', 'language_code' => 'da-DK', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/mads.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/21.jpg'],
            ['id' => 2590, 'voice' => 'Lotte', 'voice_id' => 'nl-aws-std-lotte', 'gender' => 'Female', 'language_code' => 'nl-NL', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/lotte.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/4.jpg'],
            ['id' => 2591, 'voice' => 'Ruben', 'voice_id' => 'nl-aws-std-ruben', 'gender' => 'Male', 'language_code' => 'nl-NL', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/ruben.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/22.jpg'],
            ['id' => 2592, 'voice' => 'Nicole', 'voice_id' => 'au-aws-std-nicole', 'gender' => 'Female', 'language_code' => 'en-AU', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/nicole.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/5.jpg'],
            ['id' => 2593, 'voice' => 'Russell', 'voice_id' => 'au-aws-std-russell', 'gender' => 'Male', 'language_code' => 'en-AU', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/russell.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/23.jpg'],
            ['id' => 2594, 'voice' => 'Olivia', 'voice_id' => 'au-aws-nrl-olivia', 'gender' => 'Female', 'language_code' => 'en-AU', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/olivia-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/6.jpg'],
            ['id' => 2595, 'voice' => 'Amy', 'voice_id' => 'gb-aws-std-amy', 'gender' => 'Female', 'language_code' => 'en-GB', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/amy.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/7.jpg'],
            ['id' => 2596, 'voice' => 'Emma', 'voice_id' => 'gb-aws-std-emma', 'gender' => 'Female', 'language_code' => 'en-GB', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/emma.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/8.jpg'],
            ['id' => 2597, 'voice' => 'Brian', 'voice_id' => 'gb-aws-std-brian', 'gender' => 'Male', 'language_code' => 'en-GB', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/brian.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/24.jpg'],
            ['id' => 2598, 'voice' => 'Amy', 'voice_id' => 'gb-aws-nrl-amy', 'gender' => 'Female', 'language_code' => 'en-GB', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/amy-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/9.jpg'],
            ['id' => 2599, 'voice' => 'Emma', 'voice_id' => 'gb-aws-nrl-emma', 'gender' => 'Female', 'language_code' => 'en-GB', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/emma-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/10.jpg'],
            ['id' => 2600, 'voice' => 'Brian', 'voice_id' => 'gb-aws-nrl-brian', 'gender' => 'Male', 'language_code' => 'en-GB', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/brian-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/25.jpg'],           
            ['id' => 2601, 'voice' => 'Aditi', 'voice_id' => 'in-aws-std-aditi', 'gender' => 'Female', 'language_code' => 'en-IN', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/aditi-in.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/11.jpg'],
            ['id' => 2602, 'voice' => 'Raveena', 'voice_id' => 'in-aws-std-raveena', 'gender' => 'Female', 'language_code' => 'en-IN', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/raveena.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/12.jpg'],
            ['id' => 2603, 'voice' => 'Ivy', 'voice_id' => 'us-aws-std-ivy', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/ivy.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/13.jpg'],
            ['id' => 2604, 'voice' => 'Joanna', 'voice_id' => 'us-aws-std-joanna', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/joanna.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/14.jpg'],
            ['id' => 2605, 'voice' => 'Kendra', 'voice_id' => 'us-aws-std-kendra', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/kendra.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/15.jpg'],
            ['id' => 2606, 'voice' => 'Kimberly', 'voice_id' => 'us-aws-std-kimberly', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/kimberly.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/16.jpg'],
            ['id' => 2607, 'voice' => 'Salli', 'voice_id' => 'us-aws-std-salli', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/salli.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/17.jpg'],
            ['id' => 2608, 'voice' => 'Joey', 'voice_id' => 'us-aws-std-joey', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/joey.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/26.jpg'],
            ['id' => 2609, 'voice' => 'Justin', 'voice_id' => 'us-aws-std-justin', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/justin.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/27.jpg'],
            ['id' => 2610, 'voice' => 'Matthew', 'voice_id' => 'us-aws-std-matthew', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/matthew.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/28.jpg'],
            ['id' => 2611, 'voice' => 'Ivy', 'voice_id' => 'us-aws-nrl-ivy', 'gender' => 'Female(child)', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/ivy-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/18.jpg'],
            ['id' => 2612, 'voice' => 'Joanna', 'voice_id' => 'us-aws-nrl-joanna', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/joanna-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/19.jpg'],
            ['id' => 2613, 'voice' => 'Kendra', 'voice_id' => 'us-aws-nrl-kendra', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/kendra-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/20.jpg'],
            ['id' => 2614, 'voice' => 'Kimberly', 'voice_id' => 'us-aws-nrl-kimberly', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/kimberly-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/1.jpg'],
            ['id' => 2615, 'voice' => 'Salli', 'voice_id' => 'us-aws-nrl-salli', 'gender' => 'Female', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/salli-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/2.jpg'],
            ['id' => 2616, 'voice' => 'Joey', 'voice_id' => 'us-aws-nrl-joey', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/joey-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/29.jpg'],
            ['id' => 2617, 'voice' => 'Justin', 'voice_id' => 'us-aws-nrl-justin', 'gender' => 'Male(child)', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/justin-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/30.jpg'],
            ['id' => 2618, 'voice' => 'Kevin', 'voice_id' => 'us-aws-nrl-kevin', 'gender' => 'Male(child)', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/kevin-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/31.jpg'],
            ['id' => 2619, 'voice' => 'Matthew', 'voice_id' => 'us-aws-nrl-matthew', 'gender' => 'Male', 'language_code' => 'en-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/matthew-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/32.jpg'],
            ['id' => 2620, 'voice' => 'Geraint', 'voice_id' => 'wls-aws-std-matthew', 'gender' => 'Male', 'language_code' => 'en-GB-WLS', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/geraint.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/33.jpg'],
            ['id' => 2621, 'voice' => 'Celine', 'voice_id' => 'fr-aws-std-celine', 'gender' => 'Female', 'language_code' => 'fr-FR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/celine.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/3.jpg'],
            ['id' => 2622, 'voice' => 'Lea', 'voice_id' => 'fr-aws-std-lea', 'gender' => 'Female', 'language_code' => 'fr-FR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/lea.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/4.jpg'],
            ['id' => 2623, 'voice' => 'Mathieu', 'voice_id' => 'fr-aws-std-mathieu', 'gender' => 'Male', 'language_code' => 'fr-FR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/mathieu.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/34.jpg'],
            ['id' => 2624, 'voice' => 'Chantal', 'voice_id' => 'ca-aws-std-chantal', 'gender' => 'Female', 'language_code' => 'fr-CA', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/chantal.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/5.jpg'],
            ['id' => 2625, 'voice' => 'Gabrielle', 'voice_id' => 'ca-aws-nrl-gabrielle', 'gender' => 'Female', 'language_code' => 'fr-CA', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/gabrielle-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/6.jpg'],
            ['id' => 2626, 'voice' => 'Marlene', 'voice_id' => 'de-aws-std-marlene', 'gender' => 'Female', 'language_code' => 'de-DE', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/marlene.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/7.jpg'],
            ['id' => 2627, 'voice' => 'Vicki', 'voice_id' => 'de-aws-std-vicki', 'gender' => 'Female', 'language_code' => 'de-DE', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/vicki.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/8.jpg'],
            ['id' => 2628, 'voice' => 'Hans', 'voice_id' => 'de-aws-std-hans', 'gender' => 'Male', 'language_code' => 'de-DE', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/hans.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/35.jpg'],
            ['id' => 2629, 'voice' => 'Aditi', 'voice_id' => 'hi-aws-std-aditi', 'gender' => 'Female', 'language_code' => 'hi-IN', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/aditi.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/9.jpg'],
            ['id' => 2630, 'voice' => 'Dora', 'voice_id' => 'is-aws-std-dora', 'gender' => 'Female', 'language_code' => 'is-IS', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/dora.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/10.jpg'],
            ['id' => 2631, 'voice' => 'Karl', 'voice_id' => 'is-aws-std-karl', 'gender' => 'Male', 'language_code' => 'is-IS', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/karl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/36.jpg'],
            ['id' => 2632, 'voice' => 'Carla', 'voice_id' => 'it-aws-std-carla', 'gender' => 'Female', 'language_code' => 'it-IT', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/carla.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/11.jpg'],
            ['id' => 2633, 'voice' => 'Bianca', 'voice_id' => 'it-aws-std-bianca', 'gender' => 'Female', 'language_code' => 'it-IT', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/bianca.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/12.jpg'],
            ['id' => 2634, 'voice' => 'Giorgio', 'voice_id' => 'it-aws-std-giorgio', 'gender' => 'Male', 'language_code' => 'it-IT', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/giorgio.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/37.jpg'],
            ['id' => 2635, 'voice' => 'Mizuki', 'voice_id' => 'jp-aws-std-mizuki', 'gender' => 'Female', 'language_code' => 'ja-JP', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/mizuki.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/13.jpg'],
            ['id' => 2636, 'voice' => 'Takumi', 'voice_id' => 'jp-aws-std-takumi', 'gender' => 'Male', 'language_code' => 'ja-JP', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/takumi.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/38.jpg'],
            ['id' => 2637, 'voice' => 'Seoyeon', 'voice_id' => 'kr-aws-std-seoyeon', 'gender' => 'Female', 'language_code' => 'ko-KR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/seoyeon.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/14.jpg'],
            ['id' => 2638, 'voice' => 'Seoyeon', 'voice_id' => 'kr-aws-nrl-seoyeon', 'gender' => 'Female', 'language_code' => 'ko-KR', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/seoyeon-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/15.jpg'],
            ['id' => 2639, 'voice' => 'Liv', 'voice_id' => 'no-aws-std-liv', 'gender' => 'Female', 'language_code' => 'nb-NO', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/liv.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/16.jpg'],
            ['id' => 2640, 'voice' => 'Ewa', 'voice_id' => 'pl-aws-std-ewa', 'gender' => 'Female', 'language_code' => 'pl-PL', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/ewa.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/17.jpg'],
            ['id' => 2641, 'voice' => 'Maja', 'voice_id' => 'pl-aws-std-maja', 'gender' => 'Female', 'language_code' => 'pl-PL', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/maja.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/18.jpg'],
            ['id' => 2642, 'voice' => 'Jacek', 'voice_id' => 'pl-aws-std-jacek', 'gender' => 'Male', 'language_code' => 'pl-PL', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/jacek.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/39.jpg'],
            ['id' => 2643, 'voice' => 'Jan', 'voice_id' => 'pl-aws-std-jan', 'gender' => 'Male', 'language_code' => 'pl-PL', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/jan.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/40.jpg'],
            ['id' => 2644, 'voice' => 'Camila', 'voice_id' => 'br-aws-std-camila', 'gender' => 'Female', 'language_code' => 'pt-BR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/camila.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/19.jpg'],
            ['id' => 2645, 'voice' => 'Victoria', 'voice_id' => 'br-aws-std-victoria', 'gender' => 'Female', 'language_code' => 'pt-BR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/victoria.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/20.jpg'],
            ['id' => 2646, 'voice' => 'Ricardo', 'voice_id' => 'br-aws-std-ricardo', 'gender' => 'Male', 'language_code' => 'pt-BR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/ricardo.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/21.jpg'],
            ['id' => 2647, 'voice' => 'Camila', 'voice_id' => 'br-aws-nrl-camila', 'gender' => 'Female', 'language_code' => 'pt-BR', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/camila-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/1.jpg'],
            ['id' => 2648, 'voice' => 'Ines', 'voice_id' => 'pt-aws-std-ines', 'gender' => 'Female', 'language_code' => 'pt-PT', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/ines.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/2.jpg'],
            ['id' => 2649, 'voice' => 'Cristiano', 'voice_id' => 'pt-aws-std-cristiano', 'gender' => 'Male', 'language_code' => 'pt-PT', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/cristiano.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/22.jpg'],
            ['id' => 2650, 'voice' => 'Carmen', 'voice_id' => 'ro-aws-std-carment', 'gender' => 'Female', 'language_code' => 'ro-RO', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/carmen.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/3.jpg'],
            ['id' => 2651, 'voice' => 'Tatyana', 'voice_id' => 'ru-aws-std-tatyana', 'gender' => 'Female', 'language_code' => 'ru-RU', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/tatyana.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/4.jpg'],
            ['id' => 2652, 'voice' => 'Maxim', 'voice_id' => 'ru-aws-std-maxim', 'gender' => 'Male', 'language_code' => 'ru-RU', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/maxim.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/23.jpg'],
            ['id' => 2652, 'voice' => 'Conchita', 'voice_id' => 'es-aws-std-conchita', 'gender' => 'Female', 'language_code' => 'es-ES', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/conchita.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/5.jpg'],
            ['id' => 2653, 'voice' => 'Lucia', 'voice_id' => 'es-aws-std-lucia', 'gender' => 'Female', 'language_code' => 'es-ES', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/lucia.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/6.jpg'],
            ['id' => 2654, 'voice' => 'Enrique', 'voice_id' => 'es-aws-std-enrique', 'gender' => 'Male', 'language_code' => 'es-ES', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/enrique.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/24.jpg'],
            ['id' => 2655, 'voice' => 'Mia', 'voice_id' => 'mx-aws-std-mia', 'gender' => 'Female', 'language_code' => 'es-MX', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/mia.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/7.jpg'],
            ['id' => 2656, 'voice' => 'Lupe', 'voice_id' => 'us-aws-std-lupe', 'gender' => 'Female', 'language_code' => 'es-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/lupe.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/8.jpg'],
            ['id' => 2657, 'voice' => 'Penelope', 'voice_id' => 'us-aws-std-penelope', 'gender' => 'Female', 'language_code' => 'es-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/penelope.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/9.jpg'],
            ['id' => 2658, 'voice' => 'Miguel', 'voice_id' => 'us-aws-std-miguel', 'gender' => 'Male', 'language_code' => 'es-US', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/miguel.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/25.jpg'],
            ['id' => 2659, 'voice' => 'Lupe', 'voice_id' => 'us-aws-nrl-lupe', 'gender' => 'Female', 'language_code' => 'es-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/lupe-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/10.jpg'],
            ['id' => 2660, 'voice' => 'Astrid', 'voice_id' => 'se-aws-std-astrid', 'gender' => 'Female', 'language_code' => 'sv-SE', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/astrid.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/11.jpg'],
            ['id' => 2661, 'voice' => 'Filiz', 'voice_id' => 'tr-aws-std-filiz', 'gender' => 'Female', 'language_code' => 'tr-TR', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/filiz.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/12.jpg'],
            ['id' => 2662, 'voice' => 'Gwyneth', 'voice_id' => 'cy-aws-std-gwyneth', 'gender' => 'Female', 'language_code' => 'cy-GB', 'vendor_id' => 'aws_std', 'voice_type' => 'standard', 'sample_url' => '/voices/aws/gwyneth.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/13.jpg'],
            ['id' => 2663, 'voice' => 'Arlet', 'voice_id' => 'ca-aws-nrl-arlet', 'gender' => 'Female', 'language_code' => 'ca-ES', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/arlet.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/2.jpg'],    
            ['id' => 2664, 'voice' => 'Aria', 'voice_id' => 'nz-aws-nrl-aria', 'gender' => 'Female', 'language_code' => 'en-NZ', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/aria-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/3.jpg'],    
            ['id' => 2665, 'voice' => 'Ayanda', 'voice_id' => 'za-aws-nrl-ayanda', 'gender' => 'Female', 'language_code' => 'en-ZA', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/ayanda-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/4.jpg'],    
            ['id' => 2666, 'voice' => 'Lea', 'voice_id' => 'fr-aws-nrl-lea', 'gender' => 'Female', 'language_code' => 'fr-FR', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/lea-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/5.jpg'],    
            ['id' => 2667, 'voice' => 'Vicki', 'voice_id' => 'de-aws-nrl-vicki', 'gender' => 'Female', 'language_code' => 'de-DE', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/vicki-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/6.jpg'],    
            ['id' => 2668, 'voice' => 'Bianca', 'voice_id' => 'it-aws-nrl-bianca', 'gender' => 'Female', 'language_code' => 'it-IT', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/bianca-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/7.jpg'],    
            ['id' => 2669, 'voice' => 'Takumi', 'voice_id' => 'jp-aws-nrl-takumi', 'gender' => 'Male', 'language_code' => 'ja-JP', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/takumi-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/11.jpg'],    
            ['id' => 2670, 'voice' => 'Lucia', 'voice_id' => 'es-aws-nrl-lucia', 'gender' => 'Female', 'language_code' => 'es-ES', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/lucia-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/8.jpg'],    
            ['id' => 2671, 'voice' => 'Mia', 'voice_id' => 'mx-aws-nrl-mia', 'gender' => 'Female', 'language_code' => 'es-MX', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/mia-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/9.jpg'],   
            ['id' => 2672, 'voice' => 'Liam', 'voice_id' => 'ca-aws-nrl-liam', 'gender' => 'Male', 'language_code' => 'fr-CA', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/liam-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/21.jpg'],
            ['id' => 2673, 'voice' => 'Arthur', 'voice_id' => 'gb-aws-nrl-arthur', 'gender' => 'Male', 'language_code' => 'en-GB', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/arthur-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/21.jpg'],
            ['id' => 2674, 'voice' => 'Daniel', 'voice_id' => 'de-aws-nrl-daniel', 'gender' => 'Male', 'language_code' => 'de-DE', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/daniel-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/21.jpg'],
            ['id' => 2675, 'voice' => 'Pedro', 'voice_id' => 'es-aws-nrl-pedro', 'gender' => 'Male', 'language_code' => 'es-US', 'vendor_id' => 'aws_nrl', 'voice_type' => 'neural', 'sample_url' => '/voices/aws/pedro-nrl.mp3', 'status' => 'active', 'vendor' => 'aws', 'vendor_img' => '/img/csp/aws-sm.png', 'avatar_url' => '/voices/aws/avatars/21.jpg'],
        
            ];
    
        
        foreach ($voices as $voice) {
            Voice::updateOrCreate(['id' => $voice['id']], $voice);
        }
    }
}
